[default]
address = "127.0.0.1"
limits = { form = "64 kB", json = "1 MiB" }

[debug]
port = 8000
limits = { json = "10MiB" }

[nyc]
port = 9001

[release]
port = 10101
secret_key = "WRITEYOURSECRETHERE"